//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WM2010Model", "FK_Spieler_Mannschaft", "Mannschaft", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WM2010Management.Mannschaft), "Spieler", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WM2010Management.Spieler))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WM2010Model", "FK_Spiel_SpielOrt", "SpielOrt", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WM2010Management.SpielOrt), "Spiel", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WM2010Management.Spiel))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WM2010Model", "FK_Spieler_SpielPosition", "SpielPosition", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WM2010Management.SpielPosition), "Spieler", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WM2010Management.Spieler))]

// Name der Ursprungsdatei:
// Erstellungsdatum: 09.06.2010 18:35:16
namespace WM2010Management
{
    
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Entities im Schema.
    /// </summary>
    public partial class WM2010Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initialisiert ein neues WM2010Entities-Objekt mithilfe der in Abschnitt 'WM2010Entities' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public WM2010Entities() : 
                base("name=WM2010Entities", "WM2010Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialisiert ein neues WM2010Entities-Objekt.
        /// </summary>
        public WM2010Entities(string connectionString) : 
                base(connectionString, "WM2010Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialisiert ein neues WM2010Entities-Objekt.
        /// </summary>
        public WM2010Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "WM2010Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Es gibt keine Kommentare für FussballWM im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<FussballWM> FussballWM
        {
            get
            {
                if ((this._FussballWM == null))
                {
                    this._FussballWM = base.CreateQuery<FussballWM>("[FussballWM]");
                }
                return this._FussballWM;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<FussballWM> _FussballWM;
        /// <summary>
        /// Es gibt keine Kommentare für Gruppe im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Gruppe> Gruppe
        {
            get
            {
                if ((this._Gruppe == null))
                {
                    this._Gruppe = base.CreateQuery<Gruppe>("[Gruppe]");
                }
                return this._Gruppe;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Gruppe> _Gruppe;
        /// <summary>
        /// Es gibt keine Kommentare für Mannschaft im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Mannschaft> Mannschaft
        {
            get
            {
                if ((this._Mannschaft == null))
                {
                    this._Mannschaft = base.CreateQuery<Mannschaft>("[Mannschaft]");
                }
                return this._Mannschaft;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Mannschaft> _Mannschaft;
        /// <summary>
        /// Es gibt keine Kommentare für Spiel im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Spiel> Spiel
        {
            get
            {
                if ((this._Spiel == null))
                {
                    this._Spiel = base.CreateQuery<Spiel>("[Spiel]");
                }
                return this._Spiel;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Spiel> _Spiel;
        /// <summary>
        /// Es gibt keine Kommentare für Spieler im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Spieler> Spieler
        {
            get
            {
                if ((this._Spieler == null))
                {
                    this._Spieler = base.CreateQuery<Spieler>("[Spieler]");
                }
                return this._Spieler;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Spieler> _Spieler;
        /// <summary>
        /// Es gibt keine Kommentare für SpielOrt im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SpielOrt> SpielOrt
        {
            get
            {
                if ((this._SpielOrt == null))
                {
                    this._SpielOrt = base.CreateQuery<SpielOrt>("[SpielOrt]");
                }
                return this._SpielOrt;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SpielOrt> _SpielOrt;
        /// <summary>
        /// Es gibt keine Kommentare für SpielPosition im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SpielPosition> SpielPosition
        {
            get
            {
                if ((this._SpielPosition == null))
                {
                    this._SpielPosition = base.CreateQuery<SpielPosition>("[SpielPosition]");
                }
                return this._SpielPosition;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SpielPosition> _SpielPosition;
        /// <summary>
        /// Es gibt keine Kommentare für FussballWM im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToFussballWM(FussballWM fussballWM)
        {
            base.AddObject("FussballWM", fussballWM);
        }
        /// <summary>
        /// Es gibt keine Kommentare für Gruppe im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToGruppe(Gruppe gruppe)
        {
            base.AddObject("Gruppe", gruppe);
        }
        /// <summary>
        /// Es gibt keine Kommentare für Mannschaft im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMannschaft(Mannschaft mannschaft)
        {
            base.AddObject("Mannschaft", mannschaft);
        }
        /// <summary>
        /// Es gibt keine Kommentare für Spiel im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSpiel(Spiel spiel)
        {
            base.AddObject("Spiel", spiel);
        }
        /// <summary>
        /// Es gibt keine Kommentare für Spieler im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSpieler(Spieler spieler)
        {
            base.AddObject("Spieler", spieler);
        }
        /// <summary>
        /// Es gibt keine Kommentare für SpielOrt im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSpielOrt(SpielOrt spielOrt)
        {
            base.AddObject("SpielOrt", spielOrt);
        }
        /// <summary>
        /// Es gibt keine Kommentare für SpielPosition im Schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSpielPosition(SpielPosition spielPosition)
        {
            base.AddObject("SpielPosition", spielPosition);
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Model.FussballWM im Schema.
    /// </summary>
    /// <KeyProperties>
    /// FussballWMId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WM2010Model", Name="FussballWM")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FussballWM : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Erstellt ein neues FussballWM-Objekt.
        /// </summary>
        /// <param name="fussballWMId">Anfangswert von FussballWMId.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static FussballWM CreateFussballWM(int fussballWMId)
        {
            FussballWM fussballWM = new FussballWM();
            fussballWM.FussballWMId = fussballWMId;
            return fussballWM;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft FussballWMId im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int FussballWMId
        {
            get
            {
                return this._FussballWMId;
            }
            set
            {
                this.OnFussballWMIdChanging(value);
                this.ReportPropertyChanging("FussballWMId");
                this._FussballWMId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FussballWMId");
                this.OnFussballWMIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _FussballWMId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFussballWMIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFussballWMIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Land im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Land
        {
            get
            {
                return this._Land;
            }
            set
            {
                this.OnLandChanging(value);
                this.ReportPropertyChanging("Land");
                this._Land = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Land");
                this.OnLandChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Land;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLandChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLandChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SpielJahr im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> SpielJahr
        {
            get
            {
                return this._SpielJahr;
            }
            set
            {
                this.OnSpielJahrChanging(value);
                this.ReportPropertyChanging("SpielJahr");
                this._SpielJahr = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SpielJahr");
                this.OnSpielJahrChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _SpielJahr;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielJahrChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielJahrChanged();
    }
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Model.Gruppe im Schema.
    /// </summary>
    /// <KeyProperties>
    /// GruppeId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WM2010Model", Name="Gruppe")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Gruppe : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Erstellt ein neues Gruppe-Objekt.
        /// </summary>
        /// <param name="gruppeId">Anfangswert von GruppeId.</param>
        /// <param name="gruppe1">Anfangswert von Gruppe1.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Gruppe CreateGruppe(int gruppeId, string gruppe1)
        {
            Gruppe gruppe = new Gruppe();
            gruppe.GruppeId = gruppeId;
            gruppe.Gruppe1 = gruppe1;
            return gruppe;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft GruppeId im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int GruppeId
        {
            get
            {
                return this._GruppeId;
            }
            set
            {
                this.OnGruppeIdChanging(value);
                this.ReportPropertyChanging("GruppeId");
                this._GruppeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GruppeId");
                this.OnGruppeIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _GruppeId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGruppeIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGruppeIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Gruppe1 im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Gruppe1
        {
            get
            {
                return this._Gruppe1;
            }
            set
            {
                this.OnGruppe1Changing(value);
                this.ReportPropertyChanging("Gruppe1");
                this._Gruppe1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Gruppe1");
                this.OnGruppe1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Gruppe1;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGruppe1Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGruppe1Changed();
    }
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Model.Mannschaft im Schema.
    /// </summary>
    /// <KeyProperties>
    /// MannschaftId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WM2010Model", Name="Mannschaft")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Mannschaft : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Erstellt ein neues Mannschaft-Objekt.
        /// </summary>
        /// <param name="mannschaftId">Anfangswert von MannschaftId.</param>
        /// <param name="land">Anfangswert von Land.</param>
        /// <param name="gruppeID">Anfangswert von GruppeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Mannschaft CreateMannschaft(int mannschaftId, string land, int gruppeID)
        {
            Mannschaft mannschaft = new Mannschaft();
            mannschaft.MannschaftId = mannschaftId;
            mannschaft.Land = land;
            mannschaft.GruppeID = gruppeID;
            return mannschaft;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft MannschaftId im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int MannschaftId
        {
            get
            {
                return this._MannschaftId;
            }
            set
            {
                this.OnMannschaftIdChanging(value);
                this.ReportPropertyChanging("MannschaftId");
                this._MannschaftId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MannschaftId");
                this.OnMannschaftIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _MannschaftId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMannschaftIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMannschaftIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Land im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Land
        {
            get
            {
                return this._Land;
            }
            set
            {
                this.OnLandChanging(value);
                this.ReportPropertyChanging("Land");
                this._Land = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Land");
                this.OnLandChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Land;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLandChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLandChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Fahne im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte[] Fahne
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Fahne);
            }
            set
            {
                this.OnFahneChanging(value);
                this.ReportPropertyChanging("Fahne");
                this._Fahne = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Fahne");
                this.OnFahneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte[] _Fahne;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFahneChanging(byte[] value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFahneChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Tore im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Tore
        {
            get
            {
                return this._Tore;
            }
            set
            {
                this.OnToreChanging(value);
                this.ReportPropertyChanging("Tore");
                this._Tore = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Tore");
                this.OnToreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Tore;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft GegenTore im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> GegenTore
        {
            get
            {
                return this._GegenTore;
            }
            set
            {
                this.OnGegenToreChanging(value);
                this.ReportPropertyChanging("GegenTore");
                this._GegenTore = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GegenTore");
                this.OnGegenToreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _GegenTore;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGegenToreChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGegenToreChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Punkte im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Punkte
        {
            get
            {
                return this._Punkte;
            }
            set
            {
                this.OnPunkteChanging(value);
                this.ReportPropertyChanging("Punkte");
                this._Punkte = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Punkte");
                this.OnPunkteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Punkte;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPunkteChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPunkteChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft GruppeID im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int GruppeID
        {
            get
            {
                return this._GruppeID;
            }
            set
            {
                this.OnGruppeIDChanging(value);
                this.ReportPropertyChanging("GruppeID");
                this._GruppeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GruppeID");
                this.OnGruppeIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _GruppeID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGruppeIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGruppeIDChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Spieler im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WM2010Model", "FK_Spieler_Mannschaft", "Spieler")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Spieler> Spieler
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Spieler>("WM2010Model.FK_Spieler_Mannschaft", "Spieler");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Spieler>("WM2010Model.FK_Spieler_Mannschaft", "Spieler", value);
                }
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Model.Spiel im Schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WM2010Model", Name="Spiel")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Spiel : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Erstellt ein neues Spiel-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert von Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Spiel CreateSpiel(int id)
        {
            Spiel spiel = new Spiel();
            spiel.Id = id;
            return spiel;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Id im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft DatumUhrzeit im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> DatumUhrzeit
        {
            get
            {
                return this._DatumUhrzeit;
            }
            set
            {
                this.OnDatumUhrzeitChanging(value);
                this.ReportPropertyChanging("DatumUhrzeit");
                this._DatumUhrzeit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DatumUhrzeit");
                this.OnDatumUhrzeitChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _DatumUhrzeit;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDatumUhrzeitChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDatumUhrzeitChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Mannschaft1Id im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Mannschaft1Id
        {
            get
            {
                return this._Mannschaft1Id;
            }
            set
            {
                this.OnMannschaft1IdChanging(value);
                this.ReportPropertyChanging("Mannschaft1Id");
                this._Mannschaft1Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Mannschaft1Id");
                this.OnMannschaft1IdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Mannschaft1Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMannschaft1IdChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMannschaft1IdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Mannschaft2Id im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Mannschaft2Id
        {
            get
            {
                return this._Mannschaft2Id;
            }
            set
            {
                this.OnMannschaft2IdChanging(value);
                this.ReportPropertyChanging("Mannschaft2Id");
                this._Mannschaft2Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Mannschaft2Id");
                this.OnMannschaft2IdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Mannschaft2Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMannschaft2IdChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMannschaft2IdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft ToreMannschaft1 im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> ToreMannschaft1
        {
            get
            {
                return this._ToreMannschaft1;
            }
            set
            {
                this.OnToreMannschaft1Changing(value);
                this.ReportPropertyChanging("ToreMannschaft1");
                this._ToreMannschaft1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ToreMannschaft1");
                this.OnToreMannschaft1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _ToreMannschaft1;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft1Changing(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft1Changed();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft ToreMannschaft2 im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> ToreMannschaft2
        {
            get
            {
                return this._ToreMannschaft2;
            }
            set
            {
                this.OnToreMannschaft2Changing(value);
                this.ReportPropertyChanging("ToreMannschaft2");
                this._ToreMannschaft2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ToreMannschaft2");
                this.OnToreMannschaft2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _ToreMannschaft2;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft2Changing(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft2Changed();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft ToreMannschaft1Halbzeit im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> ToreMannschaft1Halbzeit
        {
            get
            {
                return this._ToreMannschaft1Halbzeit;
            }
            set
            {
                this.OnToreMannschaft1HalbzeitChanging(value);
                this.ReportPropertyChanging("ToreMannschaft1Halbzeit");
                this._ToreMannschaft1Halbzeit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ToreMannschaft1Halbzeit");
                this.OnToreMannschaft1HalbzeitChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _ToreMannschaft1Halbzeit;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft1HalbzeitChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft1HalbzeitChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft ToreMannschaft2Halbzeit im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> ToreMannschaft2Halbzeit
        {
            get
            {
                return this._ToreMannschaft2Halbzeit;
            }
            set
            {
                this.OnToreMannschaft2HalbzeitChanging(value);
                this.ReportPropertyChanging("ToreMannschaft2Halbzeit");
                this._ToreMannschaft2Halbzeit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ToreMannschaft2Halbzeit");
                this.OnToreMannschaft2HalbzeitChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _ToreMannschaft2Halbzeit;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft2HalbzeitChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnToreMannschaft2HalbzeitChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft IsVerlaengerung im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> IsVerlaengerung
        {
            get
            {
                return this._IsVerlaengerung;
            }
            set
            {
                this.OnIsVerlaengerungChanging(value);
                this.ReportPropertyChanging("IsVerlaengerung");
                this._IsVerlaengerung = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsVerlaengerung");
                this.OnIsVerlaengerungChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _IsVerlaengerung;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIsVerlaengerungChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIsVerlaengerungChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft IsElfMeter im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> IsElfMeter
        {
            get
            {
                return this._IsElfMeter;
            }
            set
            {
                this.OnIsElfMeterChanging(value);
                this.ReportPropertyChanging("IsElfMeter");
                this._IsElfMeter = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsElfMeter");
                this.OnIsElfMeterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _IsElfMeter;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIsElfMeterChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIsElfMeterChanged();
        /// <summary>
        /// Es gibt keine Kommentare für SpielOrt im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WM2010Model", "FK_Spiel_SpielOrt", "SpielOrt")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SpielOrt SpielOrt
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SpielOrt>("WM2010Model.FK_Spiel_SpielOrt", "SpielOrt").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SpielOrt>("WM2010Model.FK_Spiel_SpielOrt", "SpielOrt").Value = value;
            }
        }
        /// <summary>
        /// Es gibt keine Kommentare für SpielOrt im Schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SpielOrt> SpielOrtReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SpielOrt>("WM2010Model.FK_Spiel_SpielOrt", "SpielOrt");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SpielOrt>("WM2010Model.FK_Spiel_SpielOrt", "SpielOrt", value);
                }
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Model.Spieler im Schema.
    /// </summary>
    /// <KeyProperties>
    /// SpielerId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WM2010Model", Name="Spieler")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Spieler : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Erstellt ein neues Spieler-Objekt.
        /// </summary>
        /// <param name="spielerId">Anfangswert von SpielerId.</param>
        /// <param name="vorname">Anfangswert von Vorname.</param>
        /// <param name="nachname">Anfangswert von Nachname.</param>
        /// <param name="spielerNummer">Anfangswert von SpielerNummer.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Spieler CreateSpieler(int spielerId, string vorname, string nachname, int spielerNummer)
        {
            Spieler spieler = new Spieler();
            spieler.SpielerId = spielerId;
            spieler.Vorname = vorname;
            spieler.Nachname = nachname;
            spieler.SpielerNummer = spielerNummer;
            return spieler;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SpielerId im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SpielerId
        {
            get
            {
                return this._SpielerId;
            }
            set
            {
                this.OnSpielerIdChanging(value);
                this.ReportPropertyChanging("SpielerId");
                this._SpielerId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SpielerId");
                this.OnSpielerIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SpielerId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielerIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielerIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Vorname im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Vorname
        {
            get
            {
                return this._Vorname;
            }
            set
            {
                this.OnVornameChanging(value);
                this.ReportPropertyChanging("Vorname");
                this._Vorname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Vorname");
                this.OnVornameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Vorname;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVornameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVornameChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Nachname im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nachname
        {
            get
            {
                return this._Nachname;
            }
            set
            {
                this.OnNachnameChanging(value);
                this.ReportPropertyChanging("Nachname");
                this._Nachname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nachname");
                this.OnNachnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nachname;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNachnameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNachnameChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SpielerNummer im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SpielerNummer
        {
            get
            {
                return this._SpielerNummer;
            }
            set
            {
                this.OnSpielerNummerChanging(value);
                this.ReportPropertyChanging("SpielerNummer");
                this._SpielerNummer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SpielerNummer");
                this.OnSpielerNummerChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SpielerNummer;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielerNummerChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielerNummerChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Mannschaft im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WM2010Model", "FK_Spieler_Mannschaft", "Mannschaft")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Mannschaft Mannschaft
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mannschaft>("WM2010Model.FK_Spieler_Mannschaft", "Mannschaft").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mannschaft>("WM2010Model.FK_Spieler_Mannschaft", "Mannschaft").Value = value;
            }
        }
        /// <summary>
        /// Es gibt keine Kommentare für Mannschaft im Schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Mannschaft> MannschaftReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mannschaft>("WM2010Model.FK_Spieler_Mannschaft", "Mannschaft");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Mannschaft>("WM2010Model.FK_Spieler_Mannschaft", "Mannschaft", value);
                }
            }
        }
        /// <summary>
        /// Es gibt keine Kommentare für SpielPosition im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WM2010Model", "FK_Spieler_SpielPosition", "SpielPosition")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SpielPosition SpielPosition
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SpielPosition>("WM2010Model.FK_Spieler_SpielPosition", "SpielPosition").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SpielPosition>("WM2010Model.FK_Spieler_SpielPosition", "SpielPosition").Value = value;
            }
        }
        /// <summary>
        /// Es gibt keine Kommentare für SpielPosition im Schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SpielPosition> SpielPositionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SpielPosition>("WM2010Model.FK_Spieler_SpielPosition", "SpielPosition");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SpielPosition>("WM2010Model.FK_Spieler_SpielPosition", "SpielPosition", value);
                }
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Model.SpielOrt im Schema.
    /// </summary>
    /// <KeyProperties>
    /// SpielOrtId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WM2010Model", Name="SpielOrt")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SpielOrt : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Erstellt ein neues SpielOrt-Objekt.
        /// </summary>
        /// <param name="spielOrtId">Anfangswert von SpielOrtId.</param>
        /// <param name="ort">Anfangswert von Ort.</param>
        /// <param name="stadionName">Anfangswert von StadionName.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SpielOrt CreateSpielOrt(int spielOrtId, string ort, string stadionName)
        {
            SpielOrt spielOrt = new SpielOrt();
            spielOrt.SpielOrtId = spielOrtId;
            spielOrt.Ort = ort;
            spielOrt.StadionName = stadionName;
            return spielOrt;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SpielOrtId im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SpielOrtId
        {
            get
            {
                return this._SpielOrtId;
            }
            set
            {
                this.OnSpielOrtIdChanging(value);
                this.ReportPropertyChanging("SpielOrtId");
                this._SpielOrtId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SpielOrtId");
                this.OnSpielOrtIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SpielOrtId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielOrtIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielOrtIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Ort im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Ort
        {
            get
            {
                return this._Ort;
            }
            set
            {
                this.OnOrtChanging(value);
                this.ReportPropertyChanging("Ort");
                this._Ort = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Ort");
                this.OnOrtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Ort;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnOrtChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnOrtChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft StadionName im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string StadionName
        {
            get
            {
                return this._StadionName;
            }
            set
            {
                this.OnStadionNameChanging(value);
                this.ReportPropertyChanging("StadionName");
                this._StadionName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("StadionName");
                this.OnStadionNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _StadionName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStadionNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStadionNameChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft StadionBild im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte[] StadionBild
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._StadionBild);
            }
            set
            {
                this.OnStadionBildChanging(value);
                this.ReportPropertyChanging("StadionBild");
                this._StadionBild = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StadionBild");
                this.OnStadionBildChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte[] _StadionBild;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStadionBildChanging(byte[] value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStadionBildChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Spiel im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WM2010Model", "FK_Spiel_SpielOrt", "Spiel")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Spiel> Spiel
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Spiel>("WM2010Model.FK_Spiel_SpielOrt", "Spiel");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Spiel>("WM2010Model.FK_Spiel_SpielOrt", "Spiel", value);
                }
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für WM2010Model.SpielPosition im Schema.
    /// </summary>
    /// <KeyProperties>
    /// SpielPositionId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WM2010Model", Name="SpielPosition")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SpielPosition : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Erstellt ein neues SpielPosition-Objekt.
        /// </summary>
        /// <param name="spielPositionId">Anfangswert von SpielPositionId.</param>
        /// <param name="position">Anfangswert von Position.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SpielPosition CreateSpielPosition(int spielPositionId, string position)
        {
            SpielPosition spielPosition = new SpielPosition();
            spielPosition.SpielPositionId = spielPositionId;
            spielPosition.Position = position;
            return spielPosition;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SpielPositionId im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SpielPositionId
        {
            get
            {
                return this._SpielPositionId;
            }
            set
            {
                this.OnSpielPositionIdChanging(value);
                this.ReportPropertyChanging("SpielPositionId");
                this._SpielPositionId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SpielPositionId");
                this.OnSpielPositionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SpielPositionId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielPositionIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSpielPositionIdChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft Position im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this.ReportPropertyChanging("Position");
                this._Position = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Position");
                this.OnPositionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Position;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPositionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPositionChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Spieler im Schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WM2010Model", "FK_Spieler_SpielPosition", "Spieler")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Spieler> Spieler
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Spieler>("WM2010Model.FK_Spieler_SpielPosition", "Spieler");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Spieler>("WM2010Model.FK_Spieler_SpielPosition", "Spieler", value);
                }
            }
        }
    }
}
